[versions]
detekt = "1.23.8"
jsoup = "1.20.1"
gson = "2.13.1"
mockito-core = "5.17.0"
mockito-kotlin = "5.4.0"
mockk = "1.14.2"
rx-java = "3.1.10"
sonatype-central-upload = "1.0.3"
devtools-ksp = "2.1.21-2.0.1"
retrofit2 = "2.11.0"
moshi-kotlin = "1.15.2"
retrofit2-kotlin-coroutines-adapter = "0.9.2"
java-jwt = "4.5.0"
moshi-kotlin-codegen = "1.15.2"
kotlinx-coroutines-test = "1.10.2"
mockwebserver = "4.12.0"
bcprov-jdk15on = "1.70"

[libraries]
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito-core" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito-kotlin" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
rx-java = { group = "io.reactivex.rxjava3", name = "rxjava", version.ref = "rx-java" }


retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit2" }
converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit2" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi-kotlin" }
retrofit2-kotlin-coroutines-adapter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlin-coroutines-adapter", version.ref = "retrofit2-kotlin-coroutines-adapter" }
adapter-rxjava3 = { group = "com.squareup.retrofit2", name = "adapter-rxjava3", version.ref = "retrofit2" }
java-jwt = { group = "com.auth0", name = "java-jwt", version.ref = "java-jwt" }
moshi-kotlin-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi-kotlin-codegen" }

kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }
mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "mockwebserver" }

bcprov-jdk15on = { group = "org.bouncycastle", name = "bcprov-jdk15on", version.ref = "bcprov-jdk15on" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
sonatype-central-upload = { id = "cl.franciscosolis.sonatype-central-upload", version.ref = "sonatype-central-upload" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "devtools-ksp" }

[bundles]

